// create table
//   public.rc_member (
//     id bigint generated by default as identity,
//     nickname character varying null,
//     email character varying null,
//     latitude character varying null,
//     longitude character varying null,
//     created_at timestamp with time zone not null default now(),
//     updated_at timestamp with time zone null default now(),
//     deleted_at timestamp with time zone null,
//     constraint rc_member_pkey primary key (id)
//   ) tablespace pg_default;

export interface RcMember {
  id: number;
  nickname?: string;
  email?: string;
  latitude?: string;
  longitude?: string;
  createdAt: Date;
  updatedAt?: Date;
  deletedAt?: Date;
}
