// create table
//   public.rc_moim (
//     id bigint generated by default as identity,
//     name character varying null,
//     start_date timestamp with time zone null,
//     end_date timestamp with time zone null,
//     created_at timestamp with time zone not null default now(),
//     updated_at timestamp with time zone null,
//     status character varying null,
//     constraint rc_moim_pkey primary key (id)
//   ) tablespace pg_default;

export interface RcMoim {
  id: number;
  name?: string;
  startDate?: Date;
  endDate?: Date;
  createdAt: Date;
  updatedAt?: Date;
  status?: string;
}
