// create table
//   public.rc_party (
//     id bigint generated by default as identity,
//     moim_id bigint null,
//     name character varying null,
//     location character varying null,
//     latitude character varying null,
//     longitude character varying null,
//     status character varying null,
//     created_at timestamp with time zone not null default now(),
//     updated_at timestamp with time zone null,
//     deleted_at timestamp with time zone null,
//     constraint rc_party_pkey primary key (id)
//   ) tablespace pg_default;

export interface RcParty {
  id: number;
  moimId?: number;
  name?: string;
  location?: string;
  latitude?: string;
  longitude?: string;
  status?: string;
  createdAt: Date;
  updatedAt?: Date;
  deletedAt?: Date;
}
